apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
      - name: crud-app
        image: // Azure Container Registry Name:#{Build.BuildId}#
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        envFrom:
          - secretRef:
              name: // Azure Key Vault Name
        ports:
        - containerPort: 3000
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "// Azure Key Vault Name"
---
apiVersion: v1                
kind: Service                
metadata:
  name: crud-app-service  
spec:
  type: LoadBalancer          
  ports:
    - port: 3000              
      targetPort: 3000          
  selector:
    app: crud-app      
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: // Azure Key Vault Name
  namespace: default  
spec:
  provider: azure
  secretObjects:
    - secretName: // Azure Key Vault Name
      type: Opaque               
      data:                      
        - key: DB_HOST              
          objectName: db-host       
        - key: DB_NAME               
          objectName: db-name        
        - key: DB_PASSWORD           
          objectName: db-password   
        - key: DB_USERNAME          
          objectName: db-username  
  parameters:
    keyvaultName: // Azure Key Vault Name
    useVMManagedIdentity: "true"
    usePodIdentity: "false"
    userAssignedIdentityID: // 
    objects: |
      array:
        - |
          objectName: db-host
          objectType: secret
        - |
          objectName: db-name
          objectType: secret
        - |
          objectName: db-password
          objectType: secret
        - |
          objectName: db-username
          objectType: secret
    tenantId: // 
